

services:
  app:
    build: .
    image: rahilkzi/foodienator:latest
    container_name: codeigniter_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: codeigniter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codeigniter_db
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: codeigniter_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
# Dockerfile
